version: '3'

services: 
  mongo_db: 
    container_name: database_container 
    image: mongo:latest 
    restart: always 
    volumes: 
      - mongo_db:/data/db 

  app: 
    build: . 
    ports: 
      - 4000:3000 
    environment: 
      PORT: 4000 
      MONGO_LINK: mongodb+srv://nanhuaniket03:OLUkiDDXnHgSBB1A@cluster0.thnsi.mongodb.net/url_shortner 
    depends_on: 
      - mongo_db 

volumes: 
  mongo_db: {}
